version: "3.7"

networks:
  todo_network:

volumes:
  postgres:

services:
  app:
    image: todo-app-dev
    container_name: todo-app
    ports:
      - 8080:8080
    restart: always
    networks:
      todo_network:
    volumes:
      - ".:/app"

  nginx:
    image: nginx:stable
    container_name: todo-nginx
    ports:
      - 80:80
    restart: always
    networks:
      todo_network:
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  postgres:
    image: postgres:14.1
    container_name: todo-postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      todo_network:
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data:rw"
