version: "3.7"

networks:
  app_net:

services:
  todo:
    image: todo
    container_name: todo
    ports:
      - 8080:8080
    restart: always
    networks:
      app_net:
    volumes:
      - ".:/app"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      app_net:
    volumes:
      - "./production/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./production/certbot/www:/etc/nginx/acme_challenge:ro"
      - "./production/certbot/certificate:/etc/nginx/certificate:ro"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - "./production/certbot/www:/var/www/html:rw"
      - "./production/certbot/certificate:/etc/letsencrypt:rw"

  # Get the certificate:
  # docker-compose run --rm certbot certonly --webroot -w /var/www/html -d <domain>
