version: "3.7"

networks:
  todo_network:

services:
  app:
    image: rafaeltmbr/todo:latest
    container_name: todo-app
    ports:
      - 8080:8080
    restart: always
    networks:
      todo_network:
    volumes:
      - "./.env:/app/.env"
      - "./ormconfig.json:/app/ormconfig.json"

  nginx:
    image: nginx:stable
    container_name: todo-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      todo_network:
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./certbot/www:/etc/nginx/acme_challenge:ro"
      - "./certbot/certificate:/etc/nginx/certificate:ro"
