version: "3.7"

networks:
  todo_network:

services:
  app:
    image: todo-app
    container_name: todo-app
    ports:
      - 8080:8080
    restart: always
    networks:
      todo_network:
    volumes:
      - "../.env:/app/.env"
      - "../ormconfig.json:/app/ormconfig.json"
      - "../production:/app/production"

  nginx:
    image: nginx:stable
    container_name: todo-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      todo_network:
    environment:
      SERVER_NAME: api.rafaeltmbr.com.br
      NGINX_ENV: production
    volumes:
      - "./nginx/templates:/etc/nginx/templates:ro"
      - "./certbot/www:/etc/nginx/acme_challenge:ro"
      - "./certbot/certificate:/etc/nginx/certificate:ro"

  certbot:
    image: certbot/certbot:latest
    container_name: todo-certbot
    volumes:
      - "./certbot/www:/var/www/html:rw"
      - "./certbot/certificate:/etc/letsencrypt:rw"
