- name: Secure Copy

- description: Copy local file/directory into a remote location

- inputs:
  source:
    description: local file/directory to be copied
    required: true
  destination:
    description: destination file/directory to save the copied data
    required: true

- runs:
  using: composite
  steps:
    - name: setup ssh file
      run: |
        mkdir ~/.ssh -p
        echo "$SSH_KEY" >> ~/.ssh/key
        sudo chmod 600 ~/.ssh/key
        cat >>~/.ssh/config <<FINISH
        Host server
          Hostname $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/key
          PubKeyAuthentication yes
          StrictHostKeyChecking no
          RequestTTY no
        FINISH

    - name: copy files via scp
      run: scp -F ~/.ssh/config -qr ${{ inputs.source }} server:${{ inputs.destination }}
