name: Secure Copy

description: Copy local file/directory into a remote location

inputs:
  source:
    description: local file/directory to be copied
    required: true

  destination:
    description: destination file/directory to save the copied data
    required: true

runs:
  using: composite
  #env:
  #  SCP_SRC: "${{ inputs.source }}"
  #  SCP_DST: "${{ inputs.destination }}"
  steps:
    - name: setup ssh file
      shell: bash
      run: |
        mkdir ~/.ssh -p
        echo '$SSH_KEY' >> ~/.ssh/key
        sudo chmod 600 ~/.ssh/key
        cat >>~/.ssh/config <<FINISH
        Host server
          Hostname $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/key
          PubKeyAuthentication yes
          StrictHostKeyChecking no
          RequestTTY no
        FINISH

    - name: maker destination folder if not exists
      shell: bash
      run: ssh server 'ls ${{ inputs.source }} || mkdir -p ${{ inputs.source }}'

    - name: copy files via scp
      shell: bash
      run: scp -F ~/.ssh/config -qr ${{ inputs.destination }} server:${{ inputs.source }}
