name: Copy with Rsync

description: Copy local directories into a remote location

inputs:
  user:
    description: remote machine user
    required: true

  host:
    description: remote host
    required: true

  key:
    description: ssh identity file
    required: true

  source:
    description: local directories (separated by space) to be copied
    required: true

  destination:
    description: destination directory to save the copied data
    required: true

runs:
  using: composite
  steps:
    - name: setup ssh file
      shell: bash
      run: |
        mkdir ~/.ssh -p
        echo "${{ inputs.key }}" >> ~/.ssh/key
        sudo chmod 600 ~/.ssh/key
        cat >>~/.ssh/config <<FINISH
        Host server
          Hostname ${{ inputs.host }}
          User ${{ inputs.user }}
          IdentityFile ~/.ssh/key
          PubKeyAuthentication yes
          StrictHostKeyChecking no
          RequestTTY no
        FINISH

    - name: maker destination folder if not exists
      shell: bash
      run: ssh server "mkdir -p ${{ inputs.destination }}"

    - name: copy files via scp
      shell: bash
      run: rsync -avz ${{ inputs.source }} server:${{ inputs.destination }}
