name: SSH

description: run commands via ssh

inputs:
  user:
    description: remote machine user
    required: true

  host:
    description: remote host
    required: true

  key:
    description: ssh private key
    required: true

  command:
    description: commands to execute
    require: true

run:
  using: composite
  steps:
  steps:
    - name: setup ssh file
      shell: bash
      run: |
        mkdir ~/.ssh -p
        echo "${{ inputs.key }}" >> ~/.ssh/key
        sudo chmod 600 ~/.ssh/key
        cat >>~/.ssh/config <<FINISH
        Host server
          Hostname ${{ inputs.host }}
          User ${{ inputs.user }}
          IdentityFile ~/.ssh/key
          PubKeyAuthentication yes
          StrictHostKeyChecking no
          RequestTTY no
        FINISH

    - name: execute command
      shell: bash
      run: ssh server "${{ inputs.command }}"
