name: "Deploy process"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: production/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/todo:latest

      - name: Copy docker-compose file
        uses: ./.github/actions/rsync
        with:
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_key: ${{ secrets.SSH_KEY }}
          source: ./docker-compose.yml
          destination: ~/todo/

      - name: Setup remote container
        uses: ./.github/actions/ssh
        with:
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_key: ${{ secrets.SSH_KEY }}
          command: |
            cd ~/todo

            docker-compose -f production/docker-compose.yml down
            docker pull ${{ secrets.DOCKERHUB_USER }}/todo:latest
            docker-compose -f production/docker-compose.yml up -d

            docker exec todo-app node node_modules/.bin/typeorm migration:run
