name: "Deploy process"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      #- uses: actions/checkout@v2 # get source code
      #- uses: actions/setup-node@v2 # setup node environmet
      #  with:
      #    node-version: "16"
      #- run: yarn
      #- run: yarn build
      #- name: setup ssh file
      #  run: |
      #    mkdir ~/.ssh -p
      #    echo "$SSH_KEY" >> ~/.ssh/key
      #    sudo chmod 600 ~/.ssh/key
      #    cat >>~/.ssh/config <<FINISH
      #    Host server
      #      Hostname $SSH_HOST
      #      User $SSH_USER
      #      IdentityFile ~/.ssh/key
      #      PubKeyAuthentication yes
      #      StrictHostKeyChecking no
      #      RequestTTY no
      #    FINISH
      #- name: copy files via scp
      #  run: |
      #    ssh server "mkdir -p foo"
      #    scp -F ~/.ssh/config -qr dist server:~/foo/dist

      - name: Show runner
        run: |
          echo > runner.txt <<FINISH
          ${{ toJSON(runner) }}
          FINISH

          cat runner.txt

      - name: Show github
        run: |
          echo > github.txt <<FINISH
          ${{ toJSON(github) }}
          FINISH

          cat github.txt
