name: "Deploy process 1.0"

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # get source code
      - uses: actions/setup-node@v2 # setup node environmet
        with:
          node-version: "16"
      - run: yarn
      - run: "yarn build"

  dependencies-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # get source code
      - uses: actions/setup-node@v2 # setup node environmet
        with:
          node-version: "16"
      - run: yarn
