name: "Deploy process"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - uses: actions/checkout@v2 # get source code
      #- uses: actions/setup-node@v2 # setup node environmet
      #  with:
      #    node-version: "16"
      #- run: yarn
      #- run: yarn build

      - name: copy dist
        uses: "./.github/actions/scp"
        with:
          user: $SSH_USER
          host: $SSH_HOST
          key: ${{ secrets.SSH_KEY }}
          source: src
          destination: "~/"
