name: "Deploy process"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1
        
      - name: Make image tag
        run: echo "BUILD_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: production/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/todo:latest
            ${{ secrets.DOCKERHUB_USER }}/todo:${{ env.BUILD_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/todo:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/todo:buildcache,mode=max

      - name: Copy production folder
        uses: ./.github/actions/rsync
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: ./production
          destination: ~/todo/

      - name: Setup remote container
        uses: ./.github/actions/ssh
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          commands: |
            cd ~/todo

            docker-compose -f production/docker-compose.yml down
            docker pull ${{ secrets.DOCKERHUB_USER }}/todo:latest
            docker-compose -f production/docker-compose.yml up -d

            docker exec todo-app node node_modules/.bin/typeorm migration:run
