name: "Deploy process"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2 # get source code
      - uses: actions/setup-node@v2 # setup node environmet
        with:
          node-version: "16"
      - run: yarn
      - run: yarn build

      - name: Copy files
        uses: "./.github/actions/rsync"
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: dist production .env.example docker-compose.yml Dockerfile package.json
          destination: "~/code"

      - name: Install dependencies and run migrations
        uses: "./.github/actions/ssh"
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            docker run -dt --name deploy_node --volume "/home/ubuntu/todo:~" node:16.13.1
            docker exec deploy_node yarn --production
            docker exec deploy_node node node_modules/.bin/typeorm migration:run
            docker-compose down
            docker-compose up -d
            docker rm -f deploy_node
